# Generated by Django 2.1.7 on 2019-03-04 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0003_auto_20190221_1814'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
