# Generated by Django 2.1.7 on 2019-12-22 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Interface',
            fields=[
                ('interface_id', models.AutoField(primary_key=True, serialize=False, verbose_name='测试用例编号')),
                ('interface_name', models.CharField(max_length=128, verbose_name='接口名称')),
                ('interface_category', models.CharField(max_length=128, verbose_name='所属接口组')),
                ('interface_desc', models.CharField(max_length=256, verbose_name='接口描述')),
                ('interface_request_type', models.CharField(choices=[('get', 'GET'), ('post', 'POST'), ('put', 'PUT'), ('delete', 'DELETE'), ('head', 'HEAD'), ('options', 'OPTIONS'), ('trace', 'TRACE'), ('patch', 'PATCH'), ('connect', 'CONNECT')], max_length=20, verbose_name='请求方式')),
                ('interface_address', models.CharField(max_length=128, verbose_name='接口地址')),
                ('interface_status', models.CharField(choices=[('valid', '有效'), ('invalid', '无效')], max_length=20, verbose_name='接口状态')),
                ('interface_headers', models.CharField(max_length=256, verbose_name='接口头信息')),
                ('interface_parameters', models.CharField(max_length=256, verbose_name='接口参数')),
                ('interface_body', models.CharField(max_length=256, verbose_name='接口信息体')),
                ('interface_creator', models.CharField(max_length=128, verbose_name='创建用户')),
                ('interface_create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('interface_update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name_plural': '接口总表',
            },
        ),
        migrations.CreateModel(
            name='InterfaceGroup',
            fields=[
                ('interface_group_id', models.AutoField(primary_key=True, serialize=False, verbose_name='测试用例编号')),
                ('interface_group_name', models.CharField(max_length=128, unique=True)),
                ('interface_group_desc', models.CharField(max_length=256)),
                ('project_category', models.IntegerField(choices=[('0', '主动营销'), ('1', '数据平台'), ('2', '事件营销'), ('3', '互动赢家')])),
                ('interface_group_creator', models.CharField(max_length=128)),
                ('interface_group_create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('interface_group_update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
        ),
        migrations.CreateModel(
            name='InterfaceParamTemplate',
            fields=[
                ('interface_param_template_id', models.AutoField(primary_key=True, serialize=False, verbose_name='测试用例编号')),
                ('template_name', models.CharField(max_length=128, verbose_name='template_name')),
                ('template_desc', models.CharField(max_length=256, verbose_name='tempalte_desc')),
                ('string', models.CharField(max_length=128, verbose_name='string')),
                ('int', models.CharField(max_length=128, verbose_name='int')),
                ('number', models.CharField(max_length=128, verbose_name='number')),
                ('date', models.CharField(max_length=128, verbose_name='date')),
                ('bool', models.CharField(max_length=128, verbose_name='bool')),
                ('decimal', models.CharField(max_length=128, verbose_name='decimal')),
                ('creator', models.CharField(max_length=128, verbose_name='创建用户')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
        ),
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('test_case_id', models.AutoField(primary_key=True, serialize=False, verbose_name='测试用例编号')),
                ('test_case_name', models.CharField(max_length=128, verbose_name='用例名称')),
                ('test_case_data', models.CharField(max_length=128, verbose_name='用例数据')),
                ('creator', models.CharField(max_length=128, verbose_name='创建用户')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('interface', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interface_test_case', to='interfaceapp.Interface')),
            ],
        ),
        migrations.CreateModel(
            name='TestCaseSuit',
            fields=[
                ('test_suit_id', models.AutoField(primary_key=True, serialize=False, verbose_name='测试集编号')),
                ('test_suit_name', models.CharField(max_length=128, verbose_name='用例集名称')),
                ('param_template', models.CharField(default=None, max_length=128, verbose_name='参数模版')),
                ('creator', models.CharField(max_length=128, verbose_name='创建用户')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('interface', models.ManyToManyField(to='interfaceapp.Interface')),
                ('test_case', models.ManyToManyField(to='interfaceapp.TestCase')),
            ],
        ),
        migrations.CreateModel(
            name='TestPlan',
            fields=[
                ('test_plan_id', models.AutoField(primary_key=True, serialize=False, verbose_name='测试计划编号')),
                ('test_plan_name', models.CharField(max_length=128, verbose_name='测试计划名称')),
                ('test_plan_desc', models.CharField(max_length=128, verbose_name='测试计划描述')),
                ('creator', models.CharField(max_length=128, verbose_name='创建用户')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('test_case_suit', models.ManyToManyField(to='interfaceapp.TestCaseSuit')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='interface',
            unique_together={('interface_name', 'interface_category')},
        ),
    ]
