# Generated by Django 2.1.7 on 2019-12-24 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interfaceapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testcase',
            options={'verbose_name_plural': '测试用例总表'},
        ),
        migrations.AlterUniqueTogether(
            name='testcase',
            unique_together={('test_case_name', 'interface')},
        ),
    ]
