# Generated by Django 2.1.7 on 2019-12-30 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interfaceapp', '0002_auto_20191224_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interface',
            name='interface_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interfaceapp.InterfaceGroup', verbose_name='所属接口组'),
        ),
    ]
