# Generated by Django 2.1.7 on 2019-12-30 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interfaceapp', '0003_auto_20191230_1207'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='interface',
            unique_together={('interface_name', 'interface_category', 'interface_address')},
        ),
    ]
